name: siraj
description: "Islamic Application."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  geolocator: ^9.0.2
  flutter_bloc: ^9.1.1
  fluttertoast: ^8.2.12
  prayers_times: ^0.0.6
  cupertino_icons: ^1.0.8
  flutter_animate: ^4.5.2
  flutter_launcher_icons: ^0.13.1
  loading_animation_widget: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  ios: true
  android: true
  image_path: "assets/icons/launcher.png"

flutter:
  uses-material-design: true

  assets:
    - jsons/
    - assets/
    - assets/icons/
    - assets/images/

  fonts:
    - family: Arabic
      fonts:
        - asset: fonts/arabic/arabic.ttf
    - family: Number
      fonts:
        - asset: fonts/number/number.ttf
    - family: Quran
      fonts:
        - asset: fonts/quran/quran.ttf
